# default value: https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml

[manager]
prepend_keymap = [
  { on = "o", run = "noop", desc = "Open selected files" },
  { on = "Enter", run = "noop", desc = "Open selected files" },
]

append_keymap = [
  # customer goto
  { on = ["g", "s", "k"], run = "cd ~/go/src/git.woa.com/khaos", desc = "Go to the khaos directory" },
  { on = ["g", "s", "K"], run = "cd ~/go/src/k8s.io", desc = "Go to the Kubernetes directory" },
  { on = ["g", "s", "c"], run = "cd ~/go/src/github.com/champly", desc = "Go to the champly directory" },
  { on = ["g", "t"], run = "cd /tmp", desc = "Go to the tmp directory" },

  # customer key
  { on = ["o", "z"], run = "shell '$SHELL' --confirm --block", desc = "Open shell here" },
  { on = ["o", "n"], run = "shell nvim --confirm --block", desc = "Open nvim here" },
  # { on = ["o", "g"], run = "shell gitui --confirm --block", desc = "Open gitui here" },
  { on = ["o", "g"], run = "shell lazygit --confirm --block", desc = "Open lazygit here" },
  { on = ["o", "v"], run = "shell 'code .' --confirm --block", desc = "Open VSCode here" },
  { on = ["o", "f"], run = "shell 'open .' --confirm --block", desc = "Open finder here" },

  # plugin
  { on = "<Enter>", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
  { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
  { on = "T", run = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane" },
]
